package main

// helpText is the static help overlay shown in modeHelp. It is split
// into a "list of bindings" the user can scan, plus a hint on how to
// dismiss. Kept short and aligned so it reads well inside a popup.
var helpText = []string{
	"  tmux-qs · key bindings",
	"  SSH stale TMUX values fall back to the inline picker",
	"  Outside tmux, a plain launch attaches to the last active client session",
	"  Theme: client override or exact width match from @eink-widths (default 167,165)",
	"  LC_IS_EINK=1 auto-forces the current tmux client as e-ink",
	"  CLI: tmux-qs eink [list|set WIDTHS|add [WIDTH]|remove [WIDTH]|reset|force|unforce|status]",
	"",
	"  ↑ / ↓             move cursor",
	"  Mouse click tabs   switch Sessions / All / Waiting / Tmux / Panes / Config / Files / Commands",
	"  Mouse left click   select a list row",
	"  Mouse wheel        move cursor up/down",
	"  [ / ]              cycle source tabs when input is empty",
	"  Left / Right        cycle source tabs when input is empty",
	"  Loading            source changes keep the newest requested list",
	"  Tab               toggle session / window mode",
	"  Shift-Tab         move cursor up",
	"  Ctrl-n / Ctrl-p   move cursor",
	"  Alt-n / Alt-p     move cursor",
	"  Ctrl-j / Ctrl-k   move cursor",
	"  Alt-j / Alt-k     jump to next/prev tmux session",
	"  Alt-← / Alt-→     visit stack back/forward",
	"  Alt-q             previous session, else recent other-client session",
	"  Alt-↑ / Alt-↓     scroll preview pane",
	"  Ctrl-↑ / Ctrl-↓   recall previous/next input-box history",
	"  PgUp / PgDn       page-scroll preview pane",
	"",
	"  Enter             connect to selected entry",
	"  Alt-Enter         send input-box text to session (tmux send-keys)",
	"  Space             snippets for current session; Ctrl-s for selected target",
	"  Snippets: [ / ]     cycle All / Quick / Blocks / Agent categories",
	"                    duplicate snippet actions are shown only once",
	"  Alt-m             new empty session",
	"  Ctrl-r            rename selected session (uses input box)",
	"  Ctrl-d            kill selected tmux session (press twice to confirm)",
	"  Alt-u             undo last kill (recreate killed session)",
	"  Ctrl-v            list windows of selected session and jump",
	"  Ctrl-b            enter branch mode (git)",
	"  Ctrl-y            copy entry's directory to clipboard (OSC 52)",
	"  Alt-o             open git remote URL in browser",
	"  Alt-e             switch selected workspace / its -eink pair",
	"  Alt-v             open workspace using specified AI agent",
	"  Alt-t             apply template to selected session",
	"  Alt-i             toggle pin/unpin workspace",
	"  Alt-f             fuzzy search files in selected directory",
	"  Ctrl-,            filter by tag",
	"  Ctrl-;            filter by group",
	"  Ctrl-Space        toggle per-pane detail panel",
	"  Esc               exit / leave branch, tag, or help mode",
	"  Ctrl-c            quit",
	"",
	"  Ctrl-a            all (also fuzzy-matches git branch)",
	"  Session rows      newest tmux activity first (includes current session)",
	"  Fuzzy ranking     exact directory name first, then shortest path",
	"  Ctrl-w            sessions with waiting agents",
	"  Ctrl-t            tmux sessions (per-pane: cwd + title)",
	"  Ctrl-g            user-defined sessions (config.toml)",
	"  Ctrl-x            zoxide directories",
	"  Alt-r             zoxide under current session root",
	"  Ctrl-f            subdirs of current session (BFS, max 30) → new window",
	"  Alt-c             Cleanup view (stale/inactive sessions)",
	"  Ctrl-e            active panes view",
	"  Ctrl-h            SSH host connections view",
	"  Ctrl-o            Command Palette",
	"",
	"  ?                 toggle this help",
	"",
	"  In normal mode (vim), all insert-mode shortcuts above also work,",
	"  except j/k/G/gg/dd/yy/S/u/Space/Enter/esc/ctrl+c — those have their",
	"  own vim meanings. i/a re-enter insert mode; / clears + enters.",
}
