package main

// helpText is the static help overlay shown in modeHelp. It is split
// into a "list of bindings" the user can scan, plus a hint on how to
// dismiss. Kept short and aligned so it reads well inside a popup.
var helpText = []string{
	"  tmux-qs · key bindings",
	"",
	"  ↑ / ↓             move cursor",
	"  Tab / Shift-Tab   move cursor",
	"  Ctrl-n / Ctrl-p   move cursor",
	"  Alt-n / Alt-p     move cursor",
	"  Ctrl-j / Ctrl-k   move cursor",
	"  Alt-j / Alt-k     jump to next/prev tmux session",
	"  Alt-← / Alt-→     visit stack back/forward",
	"  Alt-↑ / Alt-↓     scroll preview pane",
	"  Ctrl-↑ / Ctrl-↓   recall previous/next input-box history",
	"  PgUp / PgDn       page-scroll preview pane",
	"",
	"  Enter             connect to selected entry",
	"  Alt-Enter         send input-box text to session (tmux send-keys)",
	"  Alt-s             choose a snippet for the selected pane",
	"  Alt-m             new empty session",
	"  Ctrl-r            rename selected session (uses input box)",
	"  Ctrl-d            kill selected tmux session (press twice to confirm)",
	"  Alt-u             undo last kill (recreate killed session)",
	"  Ctrl-v            list windows of selected session and jump",
	"  Ctrl-b            enter branch mode (git)",
	"  Ctrl-y            copy entry's directory to clipboard (OSC 52)",
	"  Alt-o             open git remote URL in browser",
	"  Alt-v             open workspace using specified AI agent",
	"  Alt-t             apply template to selected session",
	"  Alt-i             toggle pin/unpin workspace",
	"  Alt-f             fuzzy search files in selected directory",
	"  Space             toggle multi-select mark",
	"  Ctrl-,            filter by tag",
	"  Ctrl-;            filter by group",
	"  Ctrl-Space        toggle per-pane detail panel",
	"  Esc               exit / leave branch, tag, or help mode",
	"  Ctrl-c            quit",
	"",
	"  Ctrl-a            all (also fuzzy-matches git branch)",
	"  Ctrl-w            sessions with waiting agents",
	"  Ctrl-t / Ctrl-s   tmux sessions (per-pane: cwd + title)",
	"  Ctrl-g            user-defined sessions (config.toml)",
	"  Ctrl-x            zoxide directories",
	"  Alt-r             zoxide under current session root",
	"  Ctrl-f            subdirs of current session (BFS, max 30) → new window",
	"  Alt-c             Cleanup view (stale/inactive sessions)",
	"  Ctrl-e            active panes view",
	"  Ctrl-h            SSH host connections view",
	"  Ctrl-o            Command Palette",
	"",
	"  ?                 toggle this help",
	"",
	"  In normal mode (vim), all insert-mode shortcuts above also work,",
	"  except j/k/G/gg/dd/yy/S/u/Space/Enter/esc/ctrl+c — those have their",
	"  own vim meanings. i/a re-enter insert mode; / clears + enters.",
}
